### ISSUE TITLE
Revoking client role from group does not work

### ISSUE THREAD

**Issue by mfolnovic** [mayope/keycloakmigration#78]
If I try to remove a client role from a group, I get an error:

```
[ERROR] 2024-07-08 15:48:08.736 [main] KeycloakMigration - Error occurred while migrating: clean-deprecated-roles 
de.klg71.keycloakmigration.changeControl.actions.MigrationException: Group with name: GROUP_A in realm: testRealm does not have role: DELETE_USER!
        at de.klg71.keycloakmigration.changeControl.actions.group.RevokeRoleFromGroupAction.execute(RevokeRoleFromGroupAction.kt:41) ~[keycloakmigration-0.2.56.RC3-fat.jar:?]
        at de.klg71.keycloakmigration.changeControl.actions.Action.executeIt(Action.kt:37) ~[keycloakmigration-0.2.56.RC3-fat.jar:?]
```

```
id: remove-deprecated-roles
author: mfolnovic
changes:
  - revokeRoleFromGroup:
      realm: testRealm
      role: DELETE_USER
      group: GROUP_A
      clientId: test-client
```

**Comment by klg71** [comment]
Hey @mfolnovic  thanks for taking the time ! :)

**Comment by klg71** [comment]
Sry I closed it before I could actually do the release. Your change is in release 0.2.61. Could you verify it works?

**Comment by mfolnovic** [comment]
No problem, I've verified last release and it works!

Thank you very much for extremely fast release. :)
