### ISSUE TITLE
Bug: UpdateRealmAction NullPointerException (version 0.2.74)

### ISSUE THREAD

**Issue by simonhir** [mayope/keycloakmigration#93]
When migrating from 0.2.72 to 0.2.74 following exception is thrown. With 0.2.72 everything works fine. Also there is no difference whether it is a first-time execution or not.
This could probably be because of keycloak version 20.0.5 we are using, but i couldn't identify the change which introduced it or even the migration step triggering the UpdateRealmAction.
The [throwing line](https://github.com/mayope/keycloakmigration/blob/master/src/main/kotlin/de/klg71/keycloakmigration/changeControl/actions/realm/UpdateRealmAction.kt#L249) also seems to not have changed within the version bump.
```
[INFO ] 2024-11-21 08:41:11.066 [main] Action - Executing migration: UpdateRealm id: master
2024-11-21T08:41:11.189117100Z [ERROR] 2024-11-21 08:41:11.180 [main] KeycloakMigration - Migrations were unsuccessful:
2024-11-21T08:41:11.189150700Z java.lang.NullPointerException: null
2024-11-21T08:41:11.189154400Z 	at de.klg71.keycloakmigration.changeControl.actions.realm.UpdateRealmAction.execute(UpdateRealmAction.kt:249) ~[keycloakmigration.jar:?]
2024-11-21T08:41:11.189157500Z 	at de.klg71.keycloakmigration.changeControl.actions.Action.executeIt(Action.kt:37) ~[keycloakmigration.jar:?]
2024-11-21T08:41:11.189160300Z 	at de.klg71.keycloakmigration.changeControl.KeycloakMigration.execute$keycloakmigration(KeycloakMigration.kt:30) [keycloakmigration.jar:?]
2024-11-21T08:41:11.189163100Z 	at de.klg71.keycloakmigration.MainKt$migrate$1$1.invoke(Main.kt:78) [keycloakmigration.jar:?]
2024-11-21T08:41:11.189165900Z 	at de.klg71.keycloakmigration.MainKt$migrate$1$1.invoke(Main.kt:66) [keycloakmigration.jar:?]
2024-11-21T08:41:11.189178600Z 	at org.koin.core.context.GlobalContext.startKoin(GlobalContext.kt:65) [keycloakmigration.jar:?]
2024-11-21T08:41:11.189181500Z 	at org.koin.core.context.DefaultContextExtKt.startKoin(DefaultContextExt.kt:31) [keycloakmigration.jar:?]
2024-11-21T08:41:11.189184500Z 	at de.klg71.keycloakmigration.MainKt.migrate(Main.kt:66) [keycloakmigration.jar:?]
2024-11-21T08:41:11.189187400Z 	at de.klg71.keycloakmigration.MainKt$main$1.invoke(Main.kt:22) [keycloakmigration.jar:?]
2024-11-21T08:41:11.189190100Z 	at de.klg71.keycloakmigration.MainKt$main$1.invoke(Main.kt:20) [keycloakmigration.jar:?]
2024-11-21T08:41:11.189192800Z 	at com.xenomachina.argparser.SystemExitExceptionKt.mainBody(SystemExitException.kt:74) [keycloakmigration.jar:?]
2024-11-21T08:41:11.189195600Z 	at com.xenomachina.argparser.SystemExitExceptionKt.mainBody$default(SystemExitException.kt:72) [keycloakmigration.jar:?]
2024-11-21T08:41:11.189198300Z 	at de.klg71.keycloakmigration.MainKt.main(Main.kt:20) [keycloakmigration.jar:?]
2024-11-21T08:41:11.189828300Z Exception in thread "main" java.lang.NullPointerException
2024-11-21T08:41:11.189898600Z 	at de.klg71.keycloakmigration.changeControl.actions.realm.UpdateRealmAction.execute(UpdateRealmAction.kt:249)
2024-11-21T08:41:11.189928100Z 	at de.klg71.keycloakmigration.changeControl.actions.Action.executeIt(Action.kt:37)
2024-11-21T08:41:11.189932100Z 	at de.klg71.keycloakmigration.changeControl.KeycloakMigration.execute$keycloakmigration(KeycloakMigration.kt:30)
2024-11-21T08:41:11.189946800Z 	at de.klg71.keycloakmigration.MainKt$migrate$1$1.invoke(Main.kt:78)
2024-11-21T08:41:11.190243900Z 	at de.klg71.keycloakmigration.MainKt$migrate$1$1.invoke(Main.kt:66)
2024-11-21T08:41:11.190257500Z 	at org.koin.core.context.GlobalContext.startKoin(GlobalContext.kt:65)
2024-11-21T08:41:11.190260900Z 	at org.koin.core.context.DefaultContextExtKt.startKoin(DefaultContextExt.kt:31)
2024-11-21T08:41:11.190263700Z 	at de.klg71.keycloakmigration.MainKt.migrate(Main.kt:66)
2024-11-21T08:41:11.190266500Z 	at de.klg71.keycloakmigration.MainKt$main$1.invoke(Main.kt:22)
2024-11-21T08:41:11.190269200Z 	at de.klg71.keycloakmigration.MainKt$main$1.invoke(Main.kt:20)
2024-11-21T08:41:11.190271700Z 	at com.xenomachina.argparser.SystemExitExceptionKt.mainBody(SystemExitException.kt:74)
2024-11-21T08:41:11.190274600Z 	at com.xenomachina.argparser.SystemExitExceptionKt.mainBody$default(SystemExitException.kt:72)
2024-11-21T08:41:11.190300200Z 	at de.klg71.keycloakmigration.MainKt.main(Main.kt:20)
```

The complete setup used is in https://github.com/it-at-m/refarch/tree/main/stack

**Comment by devtobi** [comment]
I can confirm that this issue still affects version `0.2.75`.

**Comment by klg71** [comment]
Hey @devtobi the problem is that in `20.0.5` there are no RealmProfiles yet. Furthermore the `updateRealm` path changed. The data model of the `updateRealm` action also changed after `20.0.5`. What features are you missing in 0.2.72?

**Comment by klg71** [comment]
That would indeed be great ^^ The problem is that there is no documentation of the rest-endpoints I am using for the keycloakmigration. And I wont test all available keycloak versions on every release :/

I would advice you to checkout the repository change the "keycloakVersion" in the root "build.gradle.kts" and see if it builds.
If all tests pass you have a high propability that you can use this keycloak version.

**Comment by devtobi** [comment]
I think we can close this issue for now, we are bumping our keycloak instance to version 26 so the "bug" is no longer relevant.
@klg71
